# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/project/single/Digital_System_Design/II/project_4/project_4.srcs/sources_1/ip/BRAM_0/BRAM_0.xci
# IP: The module: 'BRAM_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/single/Digital_System_Design/II/project_4/project_4.srcs/sources_1/ip/BRAM_0/BRAM_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/project/single/Digital_System_Design/II/project_4/project_4.srcs/sources_1/ip/BRAM_0/BRAM_0.xci
# IP: The module: 'BRAM_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/single/Digital_System_Design/II/project_4/project_4.srcs/sources_1/ip/BRAM_0/BRAM_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
