# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_number/BRAM_number.xci
# IP: The module: 'BRAM_number' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_number/BRAM_number_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_number'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_number/BRAM_number.xci
# IP: The module: 'BRAM_number' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_number/BRAM_number_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_number'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
