// Generated by CIRCT firtool-1.66.0
module clock_devider(
  input  io_clk_in,
         io_reset,
  output io_clk_out
);

  reg [1:0] counter;
  always @(posedge io_clk_in) begin
    if (io_reset)
      counter <= 2'h0;
    else if (&counter)
      counter <= 2'h0;
    else
      counter <= counter + 2'h1;
  end // always @(posedge)
  assign io_clk_out = ~(counter[1]);
endmodule

module vga_sync(
  input        clock,
               reset,
  output       io_hsync,
               io_vsync,
               Ctrl_valid,
  output [9:0] Ctrl_xaddr,
               Ctrl_yaddr
);

  wire       _clock_devider_io_clk_out;
  reg  [9:0] x_cnt;
  reg  [9:0] y_cnt;
  always @(posedge _clock_devider_io_clk_out) begin
    if (reset) begin
      x_cnt <= 10'h1;
      y_cnt <= 10'h1;
    end
    else begin
      automatic logic _GEN;
      _GEN = x_cnt > 10'h31F;
      if (_GEN)
        x_cnt <= 10'h1;
      else
        x_cnt <= x_cnt + 10'h1;
      if (y_cnt > 10'h20C)
        y_cnt <= 10'h1;
      else if (_GEN)
        y_cnt <= y_cnt + 10'h1;
    end
  end // always @(posedge)
  clock_devider clock_devider (
    .io_clk_in  (clock),
    .io_reset   (reset),
    .io_clk_out (_clock_devider_io_clk_out)
  );
  assign io_hsync = x_cnt > 10'h60;
  assign io_vsync = y_cnt > 10'h2;
  assign Ctrl_valid = x_cnt > 10'h90 & x_cnt < 10'h311 & y_cnt > 10'h23 & y_cnt < 10'h204;
  assign Ctrl_xaddr = x_cnt - 10'h91;
  assign Ctrl_yaddr = y_cnt - 10'h24;
endmodule

// external module ps2mouse

module mouse_pointer(
  input         clock,
                reset,
  inout         io_ps2_clk,
                io_ps2_data,
  output        io_Left_click,
                io_Right_click,
  output [10:0] io_mouse_xpos,
  output [9:0]  io_mouse_ypos
);

  wire        _ps2_mouse_REn;
  wire [23:0] _ps2_mouse_mouse_data;
  reg         io_Left_click_REG;
  reg         io_Right_click_REG;
  reg  [10:0] reg_xpos;
  reg  [9:0]  reg_ypos;
  always @(posedge clock) begin
    io_Left_click_REG <= _ps2_mouse_mouse_data[0];
    io_Right_click_REG <= _ps2_mouse_mouse_data[1];
    if (reset) begin
      reg_xpos <= 11'h0;
      reg_ypos <= 10'h0;
    end
    else if (_ps2_mouse_REn) begin
      automatic logic [10:0] _next_xpos_T_2;
      automatic logic [9:0]  _next_ypos_T_2;
      _next_xpos_T_2 =
        reg_xpos + {{3{_ps2_mouse_mouse_data[15]}}, _ps2_mouse_mouse_data[15:8]};
      _next_ypos_T_2 =
        reg_ypos - {{2{_ps2_mouse_mouse_data[23]}}, _ps2_mouse_mouse_data[23:16]};
      if ($signed(_next_xpos_T_2) > 11'sh13F)
        reg_xpos <= 11'h140;
      else if ($signed(_next_xpos_T_2) < -11'sh13F)
        reg_xpos <= 11'h6C0;
      else
        reg_xpos <= _next_xpos_T_2;
      if ($signed(_next_ypos_T_2) > 10'shEF)
        reg_ypos <= 10'hF0;
      else if ($signed(_next_ypos_T_2) < -10'shEF)
        reg_ypos <= 10'h310;
      else
        reg_ypos <= _next_ypos_T_2;
    end
  end // always @(posedge)
  ps2mouse ps2_mouse (
    .clock      (clock),
    .reset      (reset),
    .ps2_clk    (io_ps2_clk),
    .ps2_data   (io_ps2_data),
    .REn        (_ps2_mouse_REn),
    .mouse_data (_ps2_mouse_mouse_data)
  );
  assign io_Left_click = ~io_Left_click_REG & _ps2_mouse_mouse_data[0];
  assign io_Right_click = ~io_Right_click_REG & _ps2_mouse_mouse_data[1];
  assign io_mouse_xpos = reg_xpos + 11'h140;
  assign io_mouse_ypos = reg_ypos + 10'hF0;
endmodule

// external module BRAM_pointer

module image(
  input         clock,
                io_vgaCtrl_valid,
  input  [9:0]  io_vgaCtrl_xaddr,
                io_vgaCtrl_yaddr,
  input  [10:0] io_pos_x,
  input  [9:0]  io_pos_y,
  output        io_hit,
  output [11:0] io_rgb
);

  wire io_hit_0 =
    {1'h0, io_vgaCtrl_xaddr} >= io_pos_x & {2'h0, io_vgaCtrl_xaddr} < {1'h0, io_pos_x}
    + 12'h20 & io_vgaCtrl_yaddr >= io_pos_y & {1'h0, io_vgaCtrl_yaddr} < {1'h0, io_pos_y}
    + 11'h20 & io_vgaCtrl_valid;
  BRAM_pointer bram (
    .clka  (clock),
    .ena   (io_hit_0),
    .addra
      (io_vgaCtrl_xaddr - io_pos_x[9:0] + {io_vgaCtrl_yaddr[4:0] - io_pos_y[4:0], 5'h0}),
    .douta (io_rgb)
  );
  assign io_hit = io_hit_0;
endmodule

module img_pointer(
  input         clock,
                reset,
                io_vgaCtrl_valid,
  input  [9:0]  io_vgaCtrl_xaddr,
                io_vgaCtrl_yaddr,
  output        io_hit,
  output [11:0] io_rgb,
  inout         io_ps2_clk,
                io_ps2_data,
  output        io_Left_click,
                io_Right_click,
  output [10:0] io_mouse_xpos,
  output [9:0]  io_mouse_ypos
);

  wire [10:0] _mouse_pointer_io_mouse_xpos;
  wire [9:0]  _mouse_pointer_io_mouse_ypos;
  mouse_pointer mouse_pointer (
    .clock          (clock),
    .reset          (reset),
    .io_ps2_clk     (io_ps2_clk),
    .io_ps2_data    (io_ps2_data),
    .io_Left_click  (io_Left_click),
    .io_Right_click (io_Right_click),
    .io_mouse_xpos  (_mouse_pointer_io_mouse_xpos),
    .io_mouse_ypos  (_mouse_pointer_io_mouse_ypos)
  );
  image img_p (
    .clock            (clock),
    .io_vgaCtrl_valid (io_vgaCtrl_valid),
    .io_vgaCtrl_xaddr (io_vgaCtrl_xaddr),
    .io_vgaCtrl_yaddr (io_vgaCtrl_yaddr),
    .io_pos_x         (_mouse_pointer_io_mouse_xpos),
    .io_pos_y         (_mouse_pointer_io_mouse_ypos),
    .io_hit           (io_hit),
    .io_rgb           (io_rgb)
  );
  assign io_mouse_xpos = _mouse_pointer_io_mouse_xpos;
  assign io_mouse_ypos = _mouse_pointer_io_mouse_ypos;
endmodule

// external module BRAM_framea

module image_1(
  input         clock,
                io_vgaCtrl_valid,
  input  [9:0]  io_vgaCtrl_xaddr,
                io_vgaCtrl_yaddr,
  input  [7:0]  io_pos_x,
  input         io_ena,
  output        io_hit,
  output [11:0] io_rgb
);

  wire [9:0] _GEN = {2'h0, io_pos_x};
  wire       io_hit_0 =
    io_vgaCtrl_xaddr >= _GEN & io_vgaCtrl_xaddr < {1'h0, {1'h0, io_pos_x} + 9'hC8}
    & io_vgaCtrl_yaddr > 10'h8B & io_vgaCtrl_yaddr < 10'h154 & io_ena & io_vgaCtrl_valid;
  BRAM_framea bram (
    .clka  (clock),
    .ena   (io_hit_0),
    .addra ({6'h0, io_vgaCtrl_xaddr - _GEN} + {6'h0, io_vgaCtrl_yaddr - 10'h8C} * 16'hC8),
    .douta (io_rgb)
  );
  assign io_hit = io_hit_0;
endmodule

// external module BRAM_frameb

module image_2(
  input         clock,
                io_vgaCtrl_valid,
  input  [9:0]  io_vgaCtrl_xaddr,
                io_vgaCtrl_yaddr,
  input  [8:0]  io_pos_x,
  input         io_ena,
  output        io_hit,
  output [11:0] io_rgb
);

  wire [9:0] _GEN = {1'h0, io_pos_x};
  wire       io_hit_0 =
    io_vgaCtrl_xaddr >= _GEN & io_vgaCtrl_xaddr < _GEN + 10'hC8
    & io_vgaCtrl_yaddr > 10'h8B & io_vgaCtrl_yaddr < 10'h154 & io_ena & io_vgaCtrl_valid;
  BRAM_frameb bram (
    .clka  (clock),
    .ena   (io_hit_0),
    .addra ({6'h0, io_vgaCtrl_xaddr - _GEN} + {6'h0, io_vgaCtrl_yaddr - 10'h8C} * 16'hC8),
    .douta (io_rgb)
  );
  assign io_hit = io_hit_0;
endmodule

module II_4(
  input         clock,
                reset,
  output        io_sync_hsync,
                io_sync_vsync,
  output [11:0] io_rgb,
  inout         io_ps2_clk,
                io_ps2_data
);

  wire        _img_b_io_hit;
  wire [11:0] _img_b_io_rgb;
  wire        _img_a_io_hit;
  wire [11:0] _img_a_io_rgb;
  wire        _img_pointer_io_hit;
  wire [11:0] _img_pointer_io_rgb;
  wire        _img_pointer_io_Left_click;
  wire        _img_pointer_io_Right_click;
  wire [10:0] _img_pointer_io_mouse_xpos;
  wire [9:0]  _img_pointer_io_mouse_ypos;
  wire        _vga_sync_Ctrl_valid;
  wire [9:0]  _vga_sync_Ctrl_xaddr;
  wire [9:0]  _vga_sync_Ctrl_yaddr;
  reg  [1:0]  state;
  always @(posedge clock) begin
    if (reset)
      state <= 2'h0;
    else if (state == 2'h2)
      state <= {~_img_pointer_io_Right_click, 1'h0};
    else if (state == 2'h1)
      state <= {1'h0, ~_img_pointer_io_Right_click};
    else if (|state)
      state <= 2'h1;
    else if (_img_pointer_io_Left_click) begin
      automatic logic _mouse_match_s_T_5;
      _mouse_match_s_T_5 = _img_pointer_io_mouse_ypos > 10'h8B;
      if (_img_pointer_io_mouse_xpos > 11'h45 & _img_pointer_io_mouse_xpos < 11'h10E
          & _mouse_match_s_T_5 & _img_pointer_io_mouse_ypos < 10'h154 & ~(|state))
        state <= 2'h1;
      else
        state <=
          {_img_pointer_io_mouse_xpos > 11'h171 & _img_pointer_io_mouse_xpos < 11'h23A
             & _mouse_match_s_T_5 & _img_pointer_io_mouse_ypos < 10'h154 & ~(|state),
           1'h0};
    end
    else
      state <= 2'h0;
  end // always @(posedge)
  vga_sync vga_sync (
    .clock      (clock),
    .reset      (reset),
    .io_hsync   (io_sync_hsync),
    .io_vsync   (io_sync_vsync),
    .Ctrl_valid (_vga_sync_Ctrl_valid),
    .Ctrl_xaddr (_vga_sync_Ctrl_xaddr),
    .Ctrl_yaddr (_vga_sync_Ctrl_yaddr)
  );
  img_pointer img_pointer (
    .clock            (clock),
    .reset            (reset),
    .io_vgaCtrl_valid (_vga_sync_Ctrl_valid),
    .io_vgaCtrl_xaddr (_vga_sync_Ctrl_xaddr),
    .io_vgaCtrl_yaddr (_vga_sync_Ctrl_yaddr),
    .io_hit           (_img_pointer_io_hit),
    .io_rgb           (_img_pointer_io_rgb),
    .io_ps2_clk       (io_ps2_clk),
    .io_ps2_data      (io_ps2_data),
    .io_Left_click    (_img_pointer_io_Left_click),
    .io_Right_click   (_img_pointer_io_Right_click),
    .io_mouse_xpos    (_img_pointer_io_mouse_xpos),
    .io_mouse_ypos    (_img_pointer_io_mouse_ypos)
  );
  image_1 img_a (
    .clock            (clock),
    .io_vgaCtrl_valid (_vga_sync_Ctrl_valid),
    .io_vgaCtrl_xaddr (_vga_sync_Ctrl_xaddr),
    .io_vgaCtrl_yaddr (_vga_sync_Ctrl_yaddr),
    .io_pos_x         (state == 2'h1 ? 8'hDC : 8'h46),
    .io_ena           (state != 2'h2),
    .io_hit           (_img_a_io_hit),
    .io_rgb           (_img_a_io_rgb)
  );
  image_2 img_b (
    .clock            (clock),
    .io_vgaCtrl_valid (_vga_sync_Ctrl_valid),
    .io_vgaCtrl_xaddr (_vga_sync_Ctrl_xaddr),
    .io_vgaCtrl_yaddr (_vga_sync_Ctrl_yaddr),
    .io_pos_x         (state == 2'h2 ? 9'hDC : 9'h172),
    .io_ena           (state != 2'h1),
    .io_hit           (_img_b_io_hit),
    .io_rgb           (_img_b_io_rgb)
  );
  assign io_rgb =
    _img_pointer_io_hit
      ? _img_pointer_io_rgb
      : _img_a_io_hit
          ? _img_a_io_rgb
          : _img_b_io_hit
              ? _img_b_io_rgb
              : {12{_vga_sync_Ctrl_xaddr > 10'h13 & {1'h0, _vga_sync_Ctrl_xaddr} < 11'h26C
                      & _vga_sync_Ctrl_yaddr < 10'h1E0}};
endmodule

