set_property PACKAGE_PIN W5 [get_ports clock]                     
set_property PACKAGE_PIN V17 [get_ports reset]             
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN W19 [get_ports io_change]       
set_property IOSTANDARD LVCMOS33 [get_ports io_change]
set_property PACKAGE_PIN U18 [get_ports io_write]       
set_property IOSTANDARD LVCMOS33 [get_ports io_write]
set_property PACKAGE_PIN T17 [get_ports io_read]       
set_property IOSTANDARD LVCMOS33 [get_ports io_read]

set_property PACKAGE_PIN W4 [get_ports {io_seg_sel[3]}]
set_property PACKAGE_PIN V4 [get_ports {io_seg_sel[2]}]
set_property PACKAGE_PIN U4 [get_ports {io_seg_sel[1]}]
set_property PACKAGE_PIN U2 [get_ports {io_seg_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_seg_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_seg_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_seg_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_seg_sel[0]}]

set_property PACKAGE_PIN V7 [get_ports {io_seg_led[7]}]
set_property PACKAGE_PIN W7 [get_ports {io_seg_led[0]}]
set_property PACKAGE_PIN W6 [get_ports {io_seg_led[1]}]
set_property PACKAGE_PIN U8 [get_ports {io_seg_led[2]}]
set_property PACKAGE_PIN V8 [get_ports {io_seg_led[3]}]
set_property PACKAGE_PIN U5 [get_ports {io_seg_led[4]}]
set_property PACKAGE_PIN V5 [get_ports {io_seg_led[5]}]
set_property PACKAGE_PIN U7 [get_ports {io_seg_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_seg_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_seg_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_seg_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_seg_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_seg_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_seg_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_seg_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_seg_led[0]}]

set_property PACKAGE_PIN L1 [get_ports io_full]       
set_property IOSTANDARD LVCMOS33 [get_ports io_full]
set_property PACKAGE_PIN P1 [get_ports io_empty]       
set_property IOSTANDARD LVCMOS33 [get_ports io_empty]
