# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/project/single/Digital_System_Design/II/project_2/project_2.srcs/sources_1/ip/FIFO_2/FIFO_2.xci
# IP: The module: 'FIFO_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/single/Digital_System_Design/II/project_2/project_2.srcs/sources_1/ip/FIFO_2/FIFO_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/single/Digital_System_Design/II/project_2/project_2.srcs/sources_1/ip/FIFO_2/FIFO_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/project/single/Digital_System_Design/II/project_2/project_2.srcs/sources_1/ip/FIFO_2/FIFO_2.xci
# IP: The module: 'FIFO_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/single/Digital_System_Design/II/project_2/project_2.srcs/sources_1/ip/FIFO_2/FIFO_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/project/single/Digital_System_Design/II/project_2/project_2.srcs/sources_1/ip/FIFO_2/FIFO_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
