// Generated by CIRCT firtool-1.66.0
module clock_devider(
  input  io_clk_in,
         io_reset,
  output io_clk_out
);

  reg [1:0] counter;
  always @(posedge io_clk_in) begin
    if (io_reset)
      counter <= 2'h0;
    else if (&counter)
      counter <= 2'h0;
    else
      counter <= counter + 2'h1;
  end // always @(posedge)
  assign io_clk_out = ~(counter[1]);
endmodule

module vga_sync(
  input        clock,
               reset,
  output       io_hsync,
               io_vsync,
               io_valid,
  output [9:0] xaddr,
               yaddr
);

  wire       _clock_devider_io_clk_out;
  reg  [9:0] x_cnt;
  reg  [9:0] y_cnt;
  wire       h_valid = x_cnt > 10'h90 & x_cnt < 10'h311;
  wire       v_valid = y_cnt > 10'h23 & y_cnt < 10'h204;
  reg  [9:0] xaddr_r;
  reg  [9:0] yaddr_r;
  always @(posedge _clock_devider_io_clk_out) begin
    if (reset) begin
      x_cnt <= 10'h1;
      y_cnt <= 10'h1;
    end
    else begin
      automatic logic _GEN;
      _GEN = x_cnt > 10'h31F;
      if (_GEN)
        x_cnt <= 10'h1;
      else
        x_cnt <= x_cnt + 10'h1;
      if (y_cnt > 10'h20C)
        y_cnt <= 10'h1;
      else if (_GEN)
        y_cnt <= y_cnt + 10'h1;
    end
    if (h_valid)
      xaddr_r <= x_cnt - 10'h91;
    if (v_valid)
      yaddr_r <= y_cnt - 10'h24;
  end // always @(posedge)
  clock_devider clock_devider (
    .io_clk_in  (clock),
    .io_reset   (reset),
    .io_clk_out (_clock_devider_io_clk_out)
  );
  assign io_hsync = x_cnt > 10'h60;
  assign io_vsync = y_cnt > 10'h2;
  assign io_valid = h_valid & v_valid;
  assign xaddr = xaddr_r;
  assign yaddr = yaddr_r;
endmodule

// external module BRAM_ui

module image(
  input         clock,
  input  [9:0]  io_xaddr,
                io_yaddr,
  output        io_hit,
  output [11:0] io_rgb
);

  wire [11:0] _bram_douta;
  reg         io_hit_REG;
  reg  [11:0] io_rgb_REG;
  always @(posedge clock) begin
    io_hit_REG <=
      io_xaddr > 10'hDB & io_xaddr < 10'h1A4 & io_yaddr > 10'h8B & io_yaddr < 10'h154;
    io_rgb_REG <= _bram_douta;
  end // always @(posedge)
  BRAM_ui bram (
    .clka  (clock),
    .ena   (io_hit_REG),
    .addra ({6'h0, io_xaddr - 10'hDC} + {6'h0, io_yaddr - 10'h8C} * 16'hC8),
    .douta (_bram_douta)
  );
  assign io_hit = io_hit_REG;
  assign io_rgb = io_rgb_REG;
endmodule

module II_final(
  input         clock,
                reset,
  output        io_vga_sync_hsync,
                io_vga_sync_vsync,
                io_vga_sync_valid,
  output [11:0] io_rgb
);

  wire        _img_ui_io_hit;
  wire [11:0] _img_ui_io_rgb;
  wire [9:0]  _vga_sync_xaddr;
  wire [9:0]  _vga_sync_yaddr;
  vga_sync vga_sync (
    .clock    (clock),
    .reset    (reset),
    .io_hsync (io_vga_sync_hsync),
    .io_vsync (io_vga_sync_vsync),
    .io_valid (io_vga_sync_valid),
    .xaddr    (_vga_sync_xaddr),
    .yaddr    (_vga_sync_yaddr)
  );
  image img_ui (
    .clock    (clock),
    .io_xaddr (_vga_sync_xaddr),
    .io_yaddr (_vga_sync_yaddr),
    .io_hit   (_img_ui_io_hit),
    .io_rgb   (_img_ui_io_rgb)
  );
  assign io_rgb = _img_ui_io_rgb;
endmodule

