# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga.xdc

# XDC: new/ps2.xdc

# XDC: new/utils.xdc

# IP: ip/BRAM_pointer/BRAM_pointer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_pointer || ORIG_REF_NAME==BRAM_pointer} -quiet] -quiet
