# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/utils.xdc

# XDC: new/vga.xdc

# XDC: new/ps2.xdc

# IP: ip/BRAM_ui/BRAM_ui.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_ui || ORIG_REF_NAME==BRAM_ui} -quiet] -quiet
