# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/project/single/Digital_System_Design/II/project_final/project_final.cache/wt [current_project]
set_property parent.project_path E:/project/single/Digital_System_Design/II/project_final/project_final.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/project/single/Digital_System_Design/II/project_final/project_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/project/single/Digital_System_Design/II/project_final/ui.coe
add_files E:/project/single/Digital_System_Design/II/project_final/pointer.coe
add_files E:/project/single/Digital_System_Design/II/project_final/number.coe
add_files E:/project/single/Digital_System_Design/II/project_final/button.coe
add_files E:/project/single/Digital_System_Design/II/project_final/subui.coe
read_verilog -library xil_defaultlib -sv E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/new/II-final.sv
read_verilog -library xil_defaultlib {
  E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/new/ps2_init_funcmod.v
  E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/new/ps2_read_funcmod.v
  E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/new/ps2mouse.v
}
read_ip -quiet E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_ui/BRAM_ui.xci
set_property used_in_implementation false [get_files -all e:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_ui/BRAM_ui_ooc.xdc]

read_ip -quiet E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_pointer/BRAM_pointer.xci
set_property used_in_implementation false [get_files -all e:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_pointer/BRAM_pointer_ooc.xdc]

read_ip -quiet E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_number/BRAM_number.xci
set_property used_in_implementation false [get_files -all e:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_number/BRAM_number_ooc.xdc]

read_ip -quiet E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_button/BRAM_button.xci
set_property used_in_implementation false [get_files -all e:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_button/BRAM_button_ooc.xdc]

read_ip -quiet E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_subui/BRAM_subui.xci
set_property used_in_implementation false [get_files -all e:/project/single/Digital_System_Design/II/project_final/project_final.srcs/sources_1/ip/BRAM_subui/BRAM_subui_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/constrs_1/new/utils.xdc
set_property used_in_implementation false [get_files E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/constrs_1/new/utils.xdc]

read_xdc E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/constrs_1/new/vga.xdc
set_property used_in_implementation false [get_files E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/constrs_1/new/vga.xdc]

read_xdc E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/constrs_1/new/ps2.xdc
set_property used_in_implementation false [get_files E:/project/single/Digital_System_Design/II/project_final/project_final.srcs/constrs_1/new/ps2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top II_final -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef II_final.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file II_final_utilization_synth.rpt -pb II_final_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
